# Unbound DNS resolver for Tailscale split DNS.
# Resolves internal service hostnames to the internal ingress ClusterIP.
# The internal ingress controller handles hostname-based routing to backends.
#
# This config is generated by deploy-tailscale-router.sh with the current
# internal ingress ClusterIP substituted at deploy time.

server:
  interface: 0.0.0.0
  port: 53
  access-control: 0.0.0.0/0 allow
  do-daemonize: no

  # Logging
  verbosity: 1
  log-queries: no

  # Internal services — all resolve to the internal ingress controller ClusterIP.
  # The ingress routes based on Host header to the correct backend.
  # Add new entries here when creating new internal Ingress resources.
${UNBOUND_LOCAL_DATA}
