parent=keycloak
# Configure these URLs for your deployment:
# privacyPolicyUrl=https://example.com/legal/privacy-policy/
# termsOfUseUrl=https://example.com/legal/terms-of-service/
# acceptableUsePolicyUrl=https://example.com/legal/acceptable-use-policy/
