apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-oidc-config
  namespace: files
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-oidc-config
  namespace: files
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud-oidc-config
  namespace: files
subjects:
  - kind: ServiceAccount
    name: nextcloud-oidc-config
    namespace: files
roleRef:
  kind: Role
  name: nextcloud-oidc-config
  apiGroup: rbac.authorization.k8s.io
