apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: docs
  labels:
    app.kubernetes.io/name: docs-redis
    app.kubernetes.io/part-of: mother-tree
spec:
  selector:
    io.kompose.service: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP
