when:
  - event: pull_request
  - event: push
    branch: main

depends_on: []

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  - name: build-admin-portal
    image: bash
    environment:
      CONTAINER_REGISTRY:
        from_secret: container_registry
      DOCKER_CONFIG: /home/woodpecker/.docker
    commands:
      - ci/scripts/build-image.sh admin-portal
    depends_on: []

  - name: build-account-portal
    image: bash
    environment:
      CONTAINER_REGISTRY:
        from_secret: container_registry
      DOCKER_CONFIG: /home/woodpecker/.docker
    commands:
      - ci/scripts/build-image.sh account-portal
    depends_on: []

  - name: build-roundcube
    image: bash
    environment:
      CONTAINER_REGISTRY:
        from_secret: container_registry
      DOCKER_CONFIG: /home/woodpecker/.docker
    commands:
      - ci/scripts/build-image.sh roundcube
    depends_on: []

  - name: build-k6-perf
    image: bash
    environment:
      CONTAINER_REGISTRY:
        from_secret: container_registry
      DOCKER_CONFIG: /home/woodpecker/.docker
    commands:
      - ci/scripts/build-image.sh perf
    depends_on: []
