when:
  - event: pull_request
  - event: push
    branch: main

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  - name: lease-tenant
    image: bash
    environment:
      CI: "true"
      E2E_MOTHERTREE_BASE_DOMAIN:
        from_secret: e2e_mothertree_base_domain
      E2E_MOTHERTREE_KC_REALM:
        from_secret: e2e_mothertree_kc_realm
      E2E_MOTHERTREE_KC_CLIENT_SECRET:
        from_secret: e2e_mothertree_kc_client_secret
      E2E_INNBA_BASE_DOMAIN:
        from_secret: e2e_innba_base_domain
      E2E_INNBA_KC_REALM:
        from_secret: e2e_innba_kc_realm
      E2E_INNBA_KC_CLIENT_SECRET:
        from_secret: e2e_innba_kc_client_secret
    commands:
      - ci/scripts/ci-lease-tenant.sh
