when:
  - event: pull_request
  - event: push
    branch: main

depends_on:
  - deploy-dev-stalwart
  - deploy-dev-nextcloud

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  - name: deploy-dev-calendar
    image: bash
    when:
      - event: pull_request
    environment:
      CI: "true"
      CI_VALKEY_PASSWORD:
        from_secret: ci_valkey_password
      DEPLOY_VAULT_PASSWORD:
        from_secret: deploy_vault_password
      GITHUB_PAT:
        from_secret: github_pat
      E2E_POOL1_TENANT:
        from_secret: e2e_pool1_tenant
      E2E_POOL2_TENANT:
        from_secret: e2e_pool2_tenant
      E2E_POOL1_BASE_DOMAIN:
        from_secret: e2e_pool1_base_domain
      E2E_POOL2_BASE_DOMAIN:
        from_secret: e2e_pool2_base_domain
    commands:
      - ci/scripts/ci-deploy-app.sh dev calendar
