depends_on:
  - e2e-setup

when:
  - event: pull_request
  - event: push
    branch: main

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  - name: e2e-tests
    image: bash
    environment:
      E2E_SHARD: "4/10"
      E2E_GREP_INVERT: "@heavy"
      E2E_BASE_DOMAIN:
        from_secret: e2e_base_domain
      E2E_TENANT:
        from_secret: e2e_tenant
      CI: "true"
    commands:
      - ci/scripts/e2e-playwright.sh
