depends_on:
  - e2e-setup

when:
  - event: [push, pull_request]

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  - name: e2e-tests
    image: bash
    environment:
      E2E_SHARD: "1/5"
      E2E_BASE_DOMAIN:
        from_secret: e2e_base_domain
      E2E_TENANT:
        from_secret: e2e_tenant
      CI: "true"
    commands:
      - ci/scripts/e2e-playwright.sh
