when:
  - event: [push, pull_request]

steps:
  - name: e2e-tests
    image: bash
    environment:
      E2E_SHARD: "3/3"
      E2E_BASE_DOMAIN:
        from_secret: e2e_base_domain
      E2E_TENANT:
        from_secret: e2e_tenant
      CI: "true"
    commands:
      - ci/scripts/e2e-playwright.sh
