# Coturn TURN server configuration
# Generated by Terraform

# Listening ports
listening-port=3478
tls-listening-port=5349
alt-listening-port=3479
alt-tls-listening-port=5350

# External IP address (will be set by Terraform)
external-ip=${external_ip}

# Realm
realm=${turn_realm}

# Authentication
use-auth-secret
static-auth-secret=${turn_shared_secret}

# Logging
verbose
log-file=/var/log/turnserver.log

# Security
no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1
no-sslv2
no-sslv3

# Network
relay-ip=${external_ip}
relay-device=eth0

# STUN support (enabled by default)
# No need to explicitly enable STUN - it's enabled by default

# TURN support
# No need to explicitly enable TURN - it's enabled by default

# Media relay port range
min-port=49152
max-port=65535

# User database (not used with static auth)
# userdb=/etc/turnserverdb.conf

# Certificate files (if using TLS)
# cert=/etc/ssl/certs/turnserver.crt
# pkey=/etc/ssl/private/turnserver.key

# Additional security
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# Allow all other IPs
allowed-peer-ip=0.0.0.0-255.255.255.255
